services: 
  backend:
    image: panderu/study-buddies-backend:latest 
    container_name: sb-backend
    ports: 
      - "8080:8080"
######################################################
  frontend:
    image: panderu/study-buddies-frontend:latest
    container_name: sb-frontend
    ports:
      - "3000:3000"
######################################################
  keycloak_web:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: kc-web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}

      KEYCLOAK_ADMIN: ${KC_DB_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_DB_PASSWORD}


      KC_HOSTNAME: 0.0.0.0
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
    command: start-dev
    depends_on:
      - keycloakdb
    ports:
      - '7070:8080'
######################################################
  keycloakdb:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
######################################################
volumes:
  postgres_data:
